### ISSUE TITLE
python_ast doesn't support f-strings (like `f"{hi}"`)

### ISSUE THREAD

**Issue by braxtonmckee** [APrioriInvestments/typed_python#159]
`python_ast` is an Alternative-based model for the python syntax tree. We need to ensure it covers all the major language features. In particular, it doesn't cover f-strings at all.

**Comment by braxtonmckee** [comment]
Szymon - why don't you take a look at this.  If you look in `python_ast.py` you'll see us defining a set of typed-python datastructures that model Python's syntax tree, along with two functions, `convertAlgebraicToPyAst` and `convertPyAstToAlgebraic` that we use to convert between the builtin representation you find in `ast` and the more formally declared typed_python form. It's missing a few features. Can you take a look?

**Comment by szymonlipinski** [comment]
Sure

**Comment by braxtonmckee** [comment]
you might also go through the python3.6 AST and make sure there's nothing else we're missing.

**Comment by szymonlipinski** [comment]
It looks like these ast nodes are missing from our code:

AsyncFunctionDef
AnnAssign
AsyncFor
AsyncWith
Nonlocal
Await
YieldFrom
FormattedValue
JoinedStr
Bytes
Constant
MatMult

**Comment by braxtonmckee** [comment]
Looks good. Let's implement them. At this point, we just need to ensure that we can parse code that contains these things and that we can then reproduce the code using the `reverseParseCheck` function.

Also looks like we're missing Assert?

I'm not sure what to do to produce 'Constant' nodes, as python has 'Num', 'Bytes', and 'Str' builtin, and things like True, False, and None come in as named constants.

**Comment by szymonlipinski** [comment]
The Assert has already been there.

I have added all the missing nodes: https://github.com/APrioriInvestments/nativepython/compare/szymon-dev
However, I couldn't write python code to emit Bytes and Constant, so it's not tested.

**Comment by braxtonmckee** [comment]
yeah, constant I don't know what that is. Bytes you can do with an inline
constant b"some_bytes" (kind of like an fstring but with 'b' not 'f').

**Comment by szymonlipinski** [comment]
I tried with something like `bytes(1)` but `b"1"` was the way to go.

So now I should generate proper code for the `f""`?

**Comment by braxtonmckee** [comment]
if this is done, send me a PR with commits linked to the ticket, and we'll
merge it.  Then, yeah, that's a good idea to do next. I'll make a ticket
for that next.

**Comment by szymonlipinski** [comment]
PR: https://github.com/APrioriInvestments/nativepython/pull/192
