### ISSUE TITLE
Figure out how to interact with pip.

### ISSUE THREAD

**Issue by braxtonmckee** [APrioriInvestments/typed_python#166]
We should be able to upload the three main libraries to 'pip' and send the bundled javascript along with it, so that users can just pip install this thing and have it work.

**Comment by dkrasner** [comment]
closing?

**Comment by braxtonmckee** [comment]
what do you mean? I don't think we've made any progress on this at all, no?

**Comment by braxtonmckee** [comment]
this is fixed.
