### ISSUE TITLE
Allow compilation of f-strings

### ISSUE THREAD

**Issue by braxtonmckee** [APrioriInvestments/typed_python#190]
To do this you'll need to add code to `ExpressionConversionContext.py` in the function `convert_expression_ast`. For the most part you should be able to do this in terms of existing functions and you won't need a lot of low-level stack manipulation.

if you look through the code there and in the other type wrappers, you'll note a common pattern where if a `convert_X` call returns None, that means that the code it pushed onto the current context does not return control flow (usually because it raises an Exception) and so we then immediately exit. We should follow that pattern.

Also note that you'll need to implement string 'join', which we currently don't have. I'll file a separate ticket for that. 

At that point, your code should build up a ListOf(str) and can use join to produce the final string.

When testing, we need to be careful to test the exception pathways that can be triggered when you evaluate an expression inside the f-string that throws, or if we return something there that cannot be converted to string.

**Comment by braxtonmckee** [comment]
I think the general strategy here would be to separately handle the JoinedString and FormattedValue nodes. 

For JoinedString:
* produce code that produces a new empty ListOf(str) in a variable with a unique temporary name
* for each node in the JoinedString, evaluate each subexpression. If it's not a str, throw an exception. Otherwise, push it on the temporary.
* At the end, use 'convert_method_call' on the temporary ListOf(str) to join it.

For FormattedValue:
* evaluate the primary expression. Make sure to check if it returns None because that means that evaluating that subexpression never returns control flow and so you should exit immediately in that case.
* evaluate the format_spec expression if present. I think that this is supposed to always be a string.
* Call 'convert_format' on the main expression, passing the format_spec if its present, otherwise no argument. 
* Check that the result is a string, and throw an exception if not.

On the formats, this is new functionality. We should add a 'convert_format' method to Wrapper.py `def convert_format(self, context, instance, formatSpecOrNone)` that by default simply calls 'convert_to_type' with 'str' as an argument if there is no format spec, and by default throws if there is a format spec. We can then override this behavior for arithmetic types to implement the format-string behavior (e.g. `.2f` or somesuch). But first, we should get it working without format specs.

If you want to understand how python does this internally, consider the following code:

```
class X:
    def __format__(self, formatSpec=None):
        return "X with format " + formatSpec

x = X()
f"{x:formatted_{1+2}}"
```

And you can see that python is simply calling `__format__` on `x` with a string produced by evaluating the right-hand-side of the `:` in the f-string.

**Comment by szymonlipinski** [comment]
Thanks,
I have two questions:

* How should I add and empty ListOf(str) to the stack and also get the reference then? Should this be with context.pushReference? I cannot find an example of using this this way to get the reference for further updating.

* How can I evaluate the expression of the formatted value? Is throwing this into the `convert_expression_ast` enough? The FormattedValue can contain also nodes like Call. 

The FormattedValue can contain nodes like this:

```
Name(id="h", ctx=Load())
JoinedStr(values=(Str(s="o", )))
```

but also like this, for `f"{square(a)}"`:

```
Call(func=Name(id="square", ctx=Load(),), args=(Name(id="a", ctx=Load(),)), keywords=(),)
```

**Comment by braxtonmckee** [comment]
To get a ListOf(str), you can write something like

```
anEmptyList = context.push(ListOf(str), lambda s: s.convert_default_initialize())
```

which initializes an empty stackslot of type ListOf(str), passes a reference to the lambda as 's', which then default initializes it.

If a `FormattedValue` is an expression, then `convert_expression_ast` ought to be enough.

**Comment by szymonlipinski** [comment]
Thanks. It looks like the code can be quite simple :).

However, for this https://github.com/APrioriInvestments/nativepython/compare/szymon-dev#diff-1ee3497baab2c9b836988fa5cdaec81fR739 I get two errors:

For line 761 I get 

```
  File "/home/szymon/Documents/projects/apriori/nativepython/nativepython/expression_conversion_context.py", line 761, in convert_expression_ast
    return items_to_join.convert_method_call("join", items_to_join, {})
  File "/home/szymon/Documents/projects/apriori/nativepython/nativepython/typed_expression.py", line 155, in convert_method_call
    return self.expr_type.convert_method_call(self.context, self, methodname, args, kwargs)
  File "/home/szymon/Documents/projects/apriori/nativepython/nativepython/type_wrappers/list_of_wrapper.py", line 205, in convert_method_call
    return super().convert_method_call(context, instance, methodname, args, kwargs)
  File "/home/szymon/Documents/projects/apriori/nativepython/nativepython/type_wrappers/tuple_of_wrapper.py", line 296, in convert_method_call
    return super().convert_method_call(context, instance, methodname, args, kwargs)
  File "/home/szymon/Documents/projects/apriori/nativepython/nativepython/type_wrappers/wrapper.py", line 304, in convert_method_call
    [str(a.expr_type) for a in args] +
TypeError: 'TypedExpression' object is not iterable


```

and when the line 758 is uncommented I get:
(I have removed the specific call from the tests for now, it was `{square(a)}`)

```
  File "/home/szymon/Documents/projects/apriori/nativepython/nativepython/function_conversion_context.py", line 351, in convert_statement_ast
    e = subcontext.convert_expression_ast(ast.value)
  File "/home/szymon/Documents/projects/apriori/nativepython/nativepython/expression_conversion_context.py", line 758, in convert_expression_ast
    value = self.convert_expression_ast(v.value)
  File "/home/szymon/Documents/projects/apriori/nativepython/nativepython/expression_conversion_context.py", line 685, in convert_expression_ast
    return lhs.convert_call(args, kwargs)
  File "/home/szymon/Documents/projects/apriori/nativepython/nativepython/typed_expression.py", line 152, in convert_call
    return self.expr_type.convert_call(self.context, self, args, kwargs)
  File "/home/szymon/Documents/projects/apriori/nativepython/nativepython/type_wrappers/python_object_of_type_wrapper.py", line 35, in convert_call
    raise NotImplementedError()
NotImplementedError
```

Also, I that with code, there should be a change in the `ast.matches.Name` node to call the `convert_format` function.

**Comment by braxtonmckee** [comment]
OK a few points.

1. in the base wrapper, don't throw an exception when we don't know how to
handle the code. you should call 'context.pushException' which generates
code to throw an exception.

2. you should not be explicitly switching on the subtypes of expression
below the JoinedString - you should be adding two handlers to
convert_expression_ast - one for handling JoinedStr and another for
FormattedValue.  You should not have to assume that a FormattedValue only
exists inside of a JoinedStr, or that the only types of expressions that
can be in a JoinedStr are Str and FormattedValue.  The only place you need
to call "convert_format" will be in FormattedValue.

3. The LHS of the 'join' needs to be the empty string, and you pass the
list of strings you want to join as an argument.

4. when you are calling 'append' (in the comment out code) you are not
passing a list of arguments, you are just passing one argument.  That
variable is called 'args' because it expects a list of arguments and you
are only passing one, and then when we try to iterate you get an exception.

**Comment by szymonlipinski** [comment]
Thanks. It looks like the code without calling the format function works. The only problem I have is at https://github.com/APrioriInvestments/nativepython/compare/szymon-dev#diff-1ee3497baab2c9b836988fa5cdaec81fR742, as this results with `AttributeError: 'TypedExpression' object has no attribute 'convert_format'`.

**Comment by braxtonmckee** [comment]
Yes, you can see that TypedExpression has a corresponding method for each
'convert_X' in the wrapper class. you added convert_format, so you need to
add the same thing there as well.

**Comment by szymonlipinski** [comment]
No I get this 

```
TypeError: Can't convert from type String to type <class 'str'>
```

for this this code:

```
    def convert_format(self, context, instance, formatSpecOrNone=None):
        if formatSpecOrNone is None:
            return self.convert_to_type(context, instance, str)
        else:
            raise context.pushException(TypeError, "We don't support conversion in the base wrapper.")```

I was trying using StringWrapper and String there, but the result was exactly the same.

**Comment by braxtonmckee** [comment]
There is a weird thing where 'str' and String are different objects but
mean the same thing. Also, some functions accept normal types and
automatically upgrade them to 'wrapper' types, and some don't.

But either way,

```
        # check if there's nothing to do
        if target_type == self:
            return expr
```

should kick in if we ever try to convert something to itself. So you need
to figure out why that's not working. Also, make sure that 'self' (which is
the wrapper type) is the same type as 'instance', since that's the intended
usage here.

**Comment by szymonlipinski** [comment]
The problem can be this:

```

    def convert_format(self, format_spec):
        return self.expr_type.convert_format(self.context, self, format_spec)

```
The caller is `String`, the instance is `TypedExpression(String)`. However, whatever I do, something is always unhappy.

**Comment by braxtonmckee** [comment]
ok, what branch is this in?

**Comment by szymonlipinski** [comment]
I think I fixed it... let me clear the code and push it

**Comment by szymonlipinski** [comment]
This is the change to fix calling the type conversion https://github.com/APrioriInvestments/nativepython/compare/szymon-dev#diff-51ebf05e2389c3df5f45005e240a8140R221

I couldn't just replace the previous check, as then it failed when called with Bool.

**Comment by szymonlipinski** [comment]
I'm wondering about the format specifier. It looks like the format is quite complicated, and I cannot just use the default python code for this, right? So I need to parse it on my own, and then create the proper output string, right?

One more thing: there is not only the specifier, but also conversion like `!r` or `!s`.

**Comment by braxtonmckee** [comment]
This is merged.
