### ISSUE TITLE
Implement string joining in the compiler

### ISSUE THREAD

**Issue by braxtonmckee** [APrioriInvestments/typed_python#191]
We have string 'split' but no corresponding 'join' method.

This should be implemented as a 'convert_method_call' method. The actual string joining should be done in C++. Like the implementation of `split` which defers to `runtime_functions.string_find` which calls `nativepython_runtime_string_split` in `_runtime.cpp`.

In this case, you'll produce a function like 

```
void nativepython_runtime_string_join(StringType::layout* outString, StringType::layout* separator, ListOfType::layout* toJoin)
```

that defers to functions implemented in StringType to do the actual work. You should be able to look at the split code for examples. 

We mimic python string internals: each string uses 1,2, or 4 bytes per codepoint depending on the largest codepoint in the string. You'll need to compute the number of bytes per codepoint across all the strings, compute the appropriate size of the output string, and then bitcopy all the relevant substrings in (making sure to cast each string to the max number of bits used as you go).

The string_wrapper needs to make sure it passes a `ListOf(str)`, but the function should work for any iterable. So it should first pass the argument into a function (using `call_py_function`) that checks whether its argument is `ListOf(str)` and if not, use `call_py_function` to call something that iterates the arguments, verifies they're strings, and pushes them into a ListOf(str).

**Comment by szymonlipinski** [comment]
The layout class is.
```
    class layout {
    public:
        std::atomic<int64_t> refcount;
        typed_python_hash_type hash_cache;
        int32_t count;
        int32_t reserved;
        uint8_t* data;
    };```

The passed as list is `ListOfType::layout* toJoin`.

How can I iterate through the list if I don't have the size of the element?

**Comment by braxtonmckee** [comment]
In this case, you know you are joining a ListOf(str), so the element Type*
is String::Make(). You must ensure that this is the case from the calling
context.  Also, for the most part, the best way to interact with the layout
object is to produce the relevant list type and use that.  For instance,
you can see StringType::split has code like

```
    static ListOfType* listofstring = ListOfType::Make(StringType::Make());
    listofstring->resize((instance_ptr)&outList, 0, 0);
```

which you can see is producing the type for ListOf(str) `listofstring` and
using it to interact with the layout.

**Comment by szymonlipinski** [comment]
Thanks. It looks like there is something wrong with the code, currently it complains that the returned NoneType cannot be converted to String. https://github.com/APrioriInvestments/nativepython/compare/szymon-dev
