### ISSUE TITLE
Timestamp cell needs to show AM/PM or go to 24 hour mode

### ISSUE THREAD

**Issue by braxtonmckee** [APrioriInvestments/typed_python#193]
It's 7 pm and I'm seeing this:

![image](https://user-images.githubusercontent.com/8184708/61335709-80710b00-a7fc-11e9-8247-b2eb981cda44.png)

**Comment by braxtonmckee** [comment]
Also, check that we're adding leading zeros in front of milliseconds, because that timestamp should be pretty close to on-the-second.

**Comment by braxtonmckee** [comment]
Actually looks like it's copying the minutes over or something, because I see '7:44:00.440' now...

**Comment by dkrasner** [comment]
take a look at the playground examples on the [timestamp_mode](https://github.com/APrioriInvestments/nativepython/tree/timestamp_mode) branch. 

I made a few minor changes, including setting the display to 24h view. 

I am not 100% sure of what you mean regarding the milliseconds. I am just converting the unix float to the appropriate time and reading off the ms. 

if this looks good feel free to merge, if you need something else just let me know

**Comment by braxtonmckee** [comment]
I just pushed a commit to that branch. See the milliseconds example. I get something like this:

![image](https://user-images.githubusercontent.com/8184708/61391465-beb50b80-a88a-11e9-9b0e-6967b4dcd7d7.png)

I should be seeing different numbers of milliseconds.

Also the 24 hour clock is not working for me. In that branch, the 'defined timestamp' test rolls through 24 hours. I get this:

![image](https://user-images.githubusercontent.com/8184708/61391538-e1dfbb00-a88a-11e9-8e8f-bc39b76e7420.png)

It should be showing the 24 hour clock.  I tried hard-refreshing the browser several times to make sure I reloaded the cache.

It shouldn't be in the center. Generally, atom components like this should be left-justified (like cells.Text). If we want to center it, that should come from a container cell or somesuch.

**Comment by dkrasner** [comment]
looks like i never pushed the 24h clock change commit.. sorry about that

i fixed the milliseconds issue, or at least it looks that way. 

agreed on styling, the position and layout of these should be controlled by some parent. i removed all styling for Timestamp other than the base ms highlighting
