### ISSUE TITLE
Ensure that Alternative implements all the magic methods correctly

### ISSUE THREAD

**Issue by braxtonmckee** [APrioriInvestments/typed_python#212]
Right now you can write

```
A = Alternative("A", X={}, __str__=lambda self: "a string")

str(A.X())
```

and get the correct dispatch. Similarly with __add__. But everything else is not implemented.

**Comment by rubidge** [comment]
Which of the remaining magic methods should be supported?
__new__, __init__, __del__
__eq__, __ne__, __lt__, __gt__, __le__, __ge__, __hash__
__bytes__, __format__
__getattr__, __getattribute__, __setattr__, __delattr__, __dir__
__get__, __set__, __delete__, __set_name__, __slots__
__instancecheck__, __subclasscheck__, __class_getitem__
__length_hint__
__getitem__, __setitem__, __delitem__
__missing__, __iter__, __reversed__
__i*__ (in-place operators) 
__r*__ (reversed operators)
__complex__, __int__, __index__,__float__
__round__, __trunc__, __floor__, __ceil__
__enter__, __exit__, __await__
__aiter__, __anext__, __aenter__, __aexit__

**Comment by braxtonmckee** [comment]
I think we can exclude anything related to class initialization or async, or that's not implemented for classes. So, of your list,

these are definitely in:

    eq, ne, lt, gt, le, ge, hash bytes, format, getattr, getattribute, setattr, delattr, dir

these are just for decorators. we might implement them for classes, but I'm not sure it makes sense for alternatives:

    get, set, delete, set_name, 

not these:

    slots, instancecheck, subclasscheck, class_getitem

we don't generate this:

    length_hint

this is just for subclasses of dict:
  
    delitem missing,

these all seem like we would do it

    getitem, setitem,  iter, reversed, i* (in-place operators), r* (reversed operators), complex, int, index,float,round, trunc, floor, ceil, enter, exit

we're not going to deal with async at this point. maybe at some point in the future:

    await aiter, anext, aenter, aexit

**Comment by braxtonmckee** [comment]
This is merged.
