### ISSUE TITLE
printing of special characters (\n, \t, ...)

### ISSUE THREAD

**Issue by atzannes** [APrioriInvestments/typed_python#223]
Example:
```
>>> from typed_python import NamedTuple
>>> t = NamedTuple(name=str)
>>> n = t(name="A\nB")
>>> print(n)
(name="A\x0aB")
```
I would have expected it to print:
```
(name="A
B")
```

**Comment by braxtonmckee** [comment]
If you put a newline in a string of a python tuple, you get a repr of the inner string regardless. however, it does display it as \n, not \x0.
