### ISSUE TITLE
Compiled Dict.get produces TypeError

### ISSUE THREAD

**Issue by rubidge** [APrioriInvestments/typed_python#254]
The following code fails with the error
{TypeError}Can't call Dict(Int64->Int64).get with args of type (Int64, Int64)

```
        @Entrypoint
        def dict_get(x, y):
            return x.get(y, -1)

        x = Dict(int, int)()

        dict_get(x, 1)
```
(The interpreted code functions properly.)

**Comment by braxtonmckee** [comment]
@rubidge is this fixed now?

**Comment by rubidge** [comment]
Yes -- I can find the test and close this.

**Comment by rubidge** [comment]
The test is test_dict_get_default.
