### ISSUE TITLE
allow getting a "PointerTo" a class, and ability to interact with the class using the pointer

### ISSUE THREAD

**Issue by braxtonmckee** [APrioriInvestments/typed_python#274]
ideally, it should be easy to get a pointer to the class, and calling `.get().someMethod()` should be very efficient (e.g. not increase the refcount on the class).

**Comment by rubidge** [comment]
Is this an appropriate use case?

inst = AClass(x=0)
ptr = inst.pointerUnsafe()

ptr.get().x = 123
self.assertEqual(inst.x, 123)

**Comment by braxtonmckee** [comment]
I think this might actually be closed out, but you can look at the
functionality that's implemented and make sure it's full.

See test_class_held_pointers and test_held_class_instances in
class_types_test.

The idea is that a Class is a refcounted pointer to a HeldClass, which is
more like a C++ class (doesn't know about its own storage lifetime).  You
can use 'pointerTo' and 'refTo' to get access to references and pointers to
the 'HeldClass' inside of a class. I don't think I fully fleshed out the
model for a HeldClass inside of a Class yet.

**Comment by braxtonmckee** [comment]
This works.
