### ISSUE TITLE
Overriding __str__ or __repr__ not honored by outer object

### ISSUE THREAD

**Issue by atzannes** [APrioriInvestments/typed_python#279]
We can derive a `class` from a `NamedTuple` to attach methods to it, such as `__str__` and `__repr__`, but if that object is part of an other `NamedTuple`, and we try to print that object, the overridden `__str__` or `__repr__` method will not be used. See example below. This might be connected to Issue #156 

We may also want to test other type combinations (not just NamedTuple within class derived from NamedTuple).

(Code updated following discussion below)
```python
class A(NamedTuple(secret=str)):
    def __str__(self):
        return "***"
    def __repr__(self):
        return "###"


B = NamedTuple(x=A)

a = A(secret="112233")
b = B(x=a)

print(f"a:{a}") # -> a:***
print(f"b:{b}") # -> b:(x=(secret="112233",),) but should be b:(x="###",)
```

**Comment by atzannes** [comment]
the last line of the test code described in this issue above still prints the secret field

**Comment by braxtonmckee** [comment]
you should be overriding repr, not str.

**Comment by atzannes** [comment]
oh, got it! `str(x)` on container `x` will call `__repr__` and not `__str__` on its components :+1: 

I'll update the code in the issue
