### ISSUE TITLE
Compiled code 'is' not working correctly with types

### ISSUE THREAD

**Issue by braxtonmckee** [APrioriInvestments/typed_python#281]
I should be able to write 'type(ListOf(int)).ElementType is int` and have it work, but it doesn't. I have to use Int64 instead.

**Comment by braxtonmckee** [comment]
actually the problem is that if I print ElementType i get 'int', but it's actually Int64.

**Comment by affine-root-system** [comment]
I can't reproduce this. The behavior for me is as follows: let x be a ListOf(int) or a ListOf(Int64). Then type(x) gives ListOf(Int64), x.ElementType gives Int64, and (if x isn't empty) type(x[0]) gives int.

What behavior do we want?
