### ISSUE TITLE
`super()` doesn't work correctly in methods in Class objects.

### ISSUE THREAD

**Issue by braxtonmckee** [APrioriInvestments/typed_python#294]
Because we bypassed the usual method descriptor pattern, it can't find it. So

```
class A(Class):
  def f(self):
      ...

class B(A):
   def f(self):
      return super().f()
```

doesn't work but

```
class B(A):
   def f(self):
       return A.f(self)
```

does

**Comment by rubidge** [comment]
Looks like we have `B.MRO = (<class 'B'>, <class 'A'>)` but  `B.mro()` and `B.__mro__` don't have `<class 'A'>`.  Also `B.__bases__` is missing `<class 'A'>`, and `A.__subclasses__()` is missing `<class 'B'>`.  So I can try to do this first.
