### ISSUE TITLE
Guarding a function argument with 'OneOf' string values breaks 'ord(x[0])'

### ISSUE THREAD

**Issue by braxtonmckee** [APrioriInvestments/typed_python#316]
```
@Entrypoint
def f(x: OneOf('A', 'B')):
    return ord(x[0])
```

ought to work in the compiler but doesn't

**Comment by rubidge** [comment]
There are other operations that suffer the same problem (e.g. attributes, abs, unary operators) -- will try to support them all.

**Comment by rubidge** [comment]
created pull request https://github.com/APrioriInvestments/typed_python/pull/327

**Comment by rubidge** [comment]
has been merged into dev
