### ISSUE TITLE
ListOf(Int32).__index___ is not implemented

### ISSUE THREAD

**Issue by aaronmlevy** [APrioriInvestments/typed_python#356]
See failing test `test_Int32_index` in `types_test.py`.

**Comment by braxtonmckee** [comment]
what do you expect here? this doesn't work in regular python either

```
x = [1, 2, 3]
x[[0]]
```
throws an exception.  Numpy allows this but not regular lists...

**Comment by aaronmlevy** [comment]
I thought you had asked me to raise this as an issue. I will remove it.
