### ISSUE TITLE
MacOS tests (OSX, python>3.7) are flaky, especially on memory usage tests

### ISSUE THREAD

**Issue by rubidge** [APrioriInvestments/typed_python#360]
Referencing https://github.com/APrioriInvestments/typed_python/commit/b417e3bb20a65c2e743499425fe98f3071692309

**Comment by rubidge** [comment]
Tried to reproduce this on OSX 10.15.6, python 3.7.7.
At the moment I'm only getting two tests to fail: test_deserialize_list_doesnt_leak and test_deserialize_set_doesnt_leak.
These fail consistently.  

memory_info().rss rises rises by 10-20 MB within the first 10 iterations.  In some cases, even iterating 100 times doesn't show a stable rss value: it can jump back and forth by 5 MB.

memory_info().vms similarly rises and fails to stabilize.

memory_full_info().uss seems more stable, however it still can rise enough to fail tests.

**Comment by rubidge** [comment]
Memory behavior is similar for serialization by itself (or deserialization by itself).  So restricting to just serialization to start with. 
Memory growth looks to be related to the serialization buffer reallocations.  
In SerializationBuffer.h, if I add 'ensure(10 * 1024 * 1024, false);' to the SerializationBuffer constructor and also set m_wants_compress(false), the memory usage will stabilize after 2 serializations (but not after only 1).

**Comment by braxtonmckee** [comment]
Why don't we just turn these off on MacOS. I think that if we have a leak in our code that it will show up on the linux tests, so if these are flaking out because of the platform we can just dispense with them.

I've been using `@pytest.mark.skipif('sys.platform=="darwin"')`

**Comment by rubidge** [comment]
This change (skipping the tests) is in dev.
