### ISSUE TITLE
str slice is sometimes corrupted; str comparison bug

### ISSUE THREAD

**Issue by rubidge** [APrioriInvestments/typed_python#362]
The StringType::getsubstr operation is corrupting multibyte characters (not copying enough bytes).

Interpreted StringType comparisons are erroneous when our StringType doesn't use smallest possible bytes_per_codepoint. Rather than force this constraint, could just add more detailed comparison logic.

(These have been addressed in branch jeff-str, not merged yet.  This issue was entered for recordkeeping.)

**Comment by rubidge** [comment]
The string comparison bug exhibited when comparing containers of strings, e.g. comparing ListOf(str) with of python list of str, and one of the StringType strings was not in lowest bytes_per_codepoint form.

**Comment by braxtonmckee** [comment]
closed by #363
