### ISSUE TITLE
Builtin math functions don't seem to compile correctly on 'object'

### ISSUE THREAD

**Issue by braxtonmckee** [APrioriInvestments/typed_python#364]
For instance, the following test fails:

```
    def test_math_functions_on_object(self):
        @Entrypoint
        def callCeil(t: object):
            return math.ceil(t)

        assert callCeil(1.5) == 2.0
```

with exception `TypeError: Can't compile '<built-in function ceil>' on instance of type 'object'`

**Comment by rubidge** [comment]
Naively, I was going to just compile this as` o.__ceil__()`.  However, float has no `__ceil__` or `__floor__` methods.  (It does have `__trunc__`.)

**Comment by rubidge** [comment]
For most math functions, any type is allowed if it has a `__float__` method. (Exception: `__trunc__`.)

**Comment by braxtonmckee** [comment]
I think the problem is that we don't have the pathway correctly set for
'PythonObjectOfType'.  That's always a tricky case because 'object' _could_
be a float, or it could be something else.  See
'027c1fea364417057b5d27e25f2f8b05dc60b46f' as an example of fixing a bug
where we handled __index__ correctly for int, float, and classes, but not
for an int/float that the compiler knows as an object.

**Comment by rubidge** [comment]
Thanks! most tests are passing now...
