### ISSUE TITLE
Accessing attributes of Held Class sometimes raises

### ISSUE THREAD

**Issue by aaronmlevy** [APrioriInvestments/typed_python#421]
Appears to be okay if we load the instance into a temporary variable, but not if we access attributes on the same line the instance is constructed.

See `test_printAttributesShouldWork` in `date_time_test.py` in 9af7203d8fb11862df9fa48aef2339876a270726

**Comment by braxtonmckee** [comment]
On what branch?

**Comment by aaronmlevy** [comment]
Branch is `aaron_timestamp`.

Commit hash is `9af7203d8fb11862df9fa48aef2339876a270726`.

**Comment by aaronmlevy** [comment]
Here's a simple test:
```
def test_printAttributesShouldWork():
    # This is okay.
    dt = DateTime(2023, 1, 2, 18, 10, 1.0)
    print(dt.date)
                                           
    # This is not.
    print(DateTime(2023, 1, 2, 18, 10, 1.0).date)
```
